### ISSUE TITLE
Adapter crashes repeatedly

### ISSUE THREAD

**Issue by Xenon-s** [iobroker-community-adapters/ioBroker.unifi-protect#180]
**Describe the bug**  
The adapter has been crashing spontaneously for several weeks. I have attached error messages

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.0.13
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1
 - Operating system: ubuntu 22.04

**Additional context**  

`<html>
<body>

host.ioBroker | 2023-08-22 10:01:15.937 | error | Caught by controller[1]: at ProtectApi.bootstrapProtect (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:114:9)
-- | -- | -- | --
host.ioBroker | 2023-08-22 10:01:15.937 | error | Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioBroker | 2023-08-22 10:01:15.937 | error | Caught by controller[1]: at ProtectApi.login (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:96:30)
host.ioBroker | 2023-08-22 10:01:15.937 | error | Caught by controller[1]: TypeError: Cannot read properties of null (reading 'headers')
host.ioBroker | 2023-08-22 10:01:15.937 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
unifi-protect.0 | 2023-08-22 10:01:15.398 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
unifi-protect.0 | 2023-08-22 10:01:15.391 | error | Cannot read properties of null (reading 'headers')
unifi-protect.0 | 2023-08-22 10:01:15.391 | error | TypeError: Cannot read properties of null (reading 'headers') at ProtectApi.login (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:96:30) at processTicksAndRejections (node:internal/process/task_queues:95:5) at ProtectApi.bootstrapProtect (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:114:9)
unifi-protect.0 | 2023-08-22 10:01:15.389 | error | unhandled promise rejection: Cannot read properties of null (reading 'headers')
unifi-protect.0 | 2023-08-22 10:01:15.389 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
unifi-protect.0 | 2023-08-22 10:01:15.388 | error | 192.168.100.1: Controller API connection terminated because it was taking too long. This error can usually be safely ignored.
host.ioBroker | 2023-08-22 10:00:56.878 | error | Caught by controller[1]: at ProtectApi.bootstrapProtect (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:114:9)
host.ioBroker | 2023-08-22 10:00:56.878 | error | Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioBroker | 2023-08-22 10:00:56.878 | error | Caught by controller[1]: at ProtectApi.login (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:96:30)
host.ioBroker | 2023-08-22 10:00:56.878 | error | Caught by controller[1]: TypeError: Cannot read properties of null (reading 'headers')
host.ioBroker | 2023-08-22 10:00:56.878 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
unifi-protect.0 | 2023-08-22 10:00:56.341 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
unifi-protect.0 | 2023-08-22 10:00:56.333 | error | Cannot read properties of null (reading 'headers')
unifi-protect.0 | 2023-08-22 10:00:56.333 | error | TypeError: Cannot read properties of null (reading 'headers') at ProtectApi.login (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:96:30) at processTicksAndRejections (node:internal/process/task_queues:95:5) at ProtectApi.bootstrapProtect (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:114:9)
unifi-protect.0 | 2023-08-22 10:00:56.332 | error | unhandled promise rejection: Cannot read properties of null (reading 'headers')
unifi-protect.0 | 2023-08-22 10:00:56.332 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
unifi-protect.0 | 2023-08-22 10:00:56.331 | error | 192.168.100.1: Controller API connection terminated because it was taking too long. This error can usually be safely ignored.
host.ioBroker | 2023-08-22 10:00:38.188 | error | Caught by controller[1]: at ProtectApi.refreshDevices (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:231:9)
host.ioBroker | 2023-08-22 10:00:38.188 | error | Caught by controller[1]: at ProtectApi.bootstrapProtect (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:114:9)
host.ioBroker | 2023-08-22 10:00:38.188 | error | Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioBroker | 2023-08-22 10:00:38.188 | error | Caught by controller[1]: at ProtectApi.login (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:96:30)
host.ioBroker | 2023-08-22 10:00:38.188 | error | Caught by controller[1]: TypeError: Cannot read properties of null (reading 'headers')
host.ioBroker | 2023-08-22 10:00:38.185 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
unifi-protect.0 | 2023-08-22 10:00:37.647 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
unifi-protect.0 | 2023-08-22 10:00:37.639 | error | Cannot read properties of null (reading 'headers')
unifi-protect.0 | 2023-08-22 10:00:37.638 | error | TypeError: Cannot read properties of null (reading 'headers') at ProtectApi.login (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:96:30) at processTicksAndRejections (node:internal/process/task_queues:95:5) at ProtectApi.bootstrapProtect (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:114:9) at ProtectApi.refreshDevices (/opt/iobroker/node_modules/iobroker.unifi-protect/protect_api/protect-api.js:231:9)
unifi-protect.0 | 2023-08-22 10:00:37.637 | error | unhandled promise rejection: Cannot read properties of null (reading 'headers')
unifi-protect.0 | 2023-08-22 10:00:37.637 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
unifi-protect.0 | 2023-08-22 10:00:37.635 | error | 192.168.100.1: Controller API connection terminated because it was taking too long. This error can usually be safely ignored.

</body>
</html>`

**Comment by Xenon-s** [comment]
new version is currently being tested on test system

**Comment by peterbaumert** [comment]
> new version is currently being tested on test system
> 
> 
> 
> [fork on github](https://github.com/Xenon-s/ioBroker.unifi-protect)

Man kann den adapter auch gern in community adapters packen oder ich geb dir rechte hier drauf

**Comment by Xenon-s** [comment]
dann pack ihn am besten in community ;)

**Comment by kailausberg** [comment]
> new version is currently being tested on test system
> 
> [fork on github](https://github.com/Xenon-s/ioBroker.unifi-protect)

Danke - läuft bei mir seit 2 Tagen damit ohne die o.a. Fehler.

**Comment by arteck** [comment]
PR plz

**Comment by mcm1957** [comment]
take a look at #343 - contains the changes done at @Xenon-s's fork.

Please note that the logging of the authorzation header should be removed for security reasons.
